// AUTO-GENERATED by scripts/generate-types.mjs
export type LeadInput = {
    name: string;
    email: string;
    phone?: (string | undefined) | "";
    interest?: (string | undefined) | "";
    message: string;
    consent?: boolean | undefined;
    utm_source?: string | undefined;
    utm_medium?: string | undefined;
    utm_campaign?: string | undefined;
    utm_content?: string | undefined;
    utm_term?: string | undefined;
    referrer?: string | undefined;
    website?: string | undefined;
}
