import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { zodToTs } from 'zod-to-ts';
import { leadSchema } from '../server/schema.js';

const { node } = zodToTs(leadSchema, 'LeadInput');
const outDir = 'src/types';
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
const content = `// AUTO-GENERATED by scripts/generate-types.mjs\nexport interface LeadInput ${node.declaration}\n`;
writeFileSync(`${outDir}/lead-input.d.ts`, content);
console.log('Generated', `${outDir}/lead-input.d.ts`);
